nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['http://172.20.10.4:3000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
