nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['http://172.20.10.4:3000', 'http://192.168.0.101:3000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
            allow_credentials: true
